[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"
  
[build.environment]
  # Firebase Configuration
  VITE_FIREBASE_API_KEY = "AIzaSyD__XrPqFeh4_K0ih4l1reNvWxjW7VItPw"
  VITE_FIREBASE_AUTH_DOMAIN = "tfimports-27898.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "tfimports-27898"
  VITE_FIREBASE_STORAGE_BUCKET = "tfimports-27898.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "379291286011"
  VITE_FIREBASE_APP_ID = "1:379291286011:web:1feb4711b5235b04c4b35e"
  VITE_FIREBASE_MEASUREMENT_ID = "G-B742BVBRES"
  
  # Asaas Configuration
  VITE_ASAAS_API_KEY = "$aact_prod_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmRhNDc4OWI0LTU4NmItNGM5Mi1iY2UxLWZhYzM0MmNjNDEyMjo6JGFhY2hfZDdkNGY5MWEtYWNlYi00N2I3LThiNGEtYWNlY2JjYzNmZmQz"
  VITE_ASAAS_ENVIRONMENT = "production"
  VITE_ASAAS_WEBHOOK_TOKEN = "tfimports_webhook_secret_2024"
  
  # Super Frete Configuration
  SUPER_FRETE_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTc2ODY5MzEsInN1YiI6Imp3Z3lTQldPTWpldWRKdUU2OVlkMDB6Y2JIVzIifQ.GFc4jbEC7hOS4qUH1tHgipigN0RglL3xjovd7f-CjDE"
  
  # Melhor Envio Configuration - REMOVIDO
  # VITE_MELHOR_ENVIO_TOKEN = "oj7uVXJfJczTN1kZfDcB9uEoPWfBHXLElI4gTPdT"
  # MELHOR_ENVIO_WEBHOOK_SECRET = "tfimports_melhor_envio_webhook_2024"
  
  # Outras configurações
  VITE_APP_ENV = "production"
  VITE_API_URL = "https://tfimports01.com.br"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://www.gstatic.com https://apis.google.com https://accounts.google.com https://*.google.com;
      style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com;
      img-src 'self' data: https:;
      connect-src 'self' https://*.firebaseapp.com https://*.googleapis.com https://apis.google.com https://firestore.googleapis.com https://viacep.com.br https://api.asaas.com https://www.asaas.com https://api.superfrete.com;
      font-src 'self' data:;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200