[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://www.gstatic.com;
      style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com;
      img-src 'self' data: https:;
      connect-src 'self' https://*.firebaseapp.com https://*.googleapis.com;
      font-src 'self' data:;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200